### ISSUE TITLE
Ping command doesn't ping

### ISSUE THREAD

**Issue by NiteBlock** [bridge-scrims/bridge-scrims-bot#38]
The ping command pings in testing but not in production

**Comment by NiteBlock** [comment]
![image](https://user-images.githubusercontent.com/47315009/156918063-99f0b007-bfe9-44b7-b8be-f6b1975112c9.jpeg)
![image](https://user-images.githubusercontent.com/47315009/156918068-12ded22a-6d00-41ea-be61-28eed3cf11d5.jpeg)

**Comment by tphere** [comment]
Finished code needs to be uploaded to GitHub for production

**Comment by NiteBlock** [comment]
It's fixed idk why it doesn't work
