### ISSUE TITLE
Staff role should have no restrictions

### ISSUE THREAD

**Issue by dtomvan** [bridge-scrims/bridge-scrims-bot#40]
Add the STAFF role to the following commands:

- [ ] /screenshare
- [ ] /close
- [ ] /ban
- [ ] /unban
- [ ] /scrimban
- [ ] /scrimunban
- [x] /ping
- [ ] /freeze
- [ ] /unfreeze

**Comment by NiteBlock** [comment]
wait why did that not work

**Comment by NiteBlock** [comment]
oops

**Comment by WhatCats** [comment]
The new interaction handler will allow server administrators to use all commands by default.
