### ISSUE TITLE
Council command not showing councils

### ISSUE THREAD

**Issue by NiteBlock** [bridge-scrims/bridge-scrims-bot#47]
The council command occasionally only had the title, I believe reloading could be the issue

**Comment by NiteBlock** [comment]
![image](https://user-images.githubusercontent.com/47315009/157382860-3a213ea0-3c0f-420f-a697-05510fff3b69.png)

**Comment by dtomvan** [comment]
We cannot reproduce. Closing for now

**Comment by dtomvan** [comment]
Nite:
> Yes, I think the splitting of init and reload fixed it

Fixed in [26d79de](https://github.com/bridge-scrims/bridge-scrims-bot/commit/26d79dee30115c0f9b12dbe31b9152839690e6a2)
