### ISSUE TITLE
Scrimunban command not working with banned role

### ISSUE THREAD

**Issue by NiteBlock** [bridge-scrims/bridge-scrims-bot#50]
The bot stores and tried to re-add the banned role if they get unbanned

**Comment by NiteBlock** [comment]
![image](https://user-images.githubusercontent.com/47315009/157705349-f48760a5-11f9-49b7-a8fb-dfbc0692f557.png)

**Comment by NiteBlock** [comment]
Expected behavior is that they get member role back, frozen role and banned role are ignored upon unban

**Comment by dtomvan** [comment]
Oh, I forgot moving the rest of the code in an `else` block

**Comment by dtomvan** [comment]
Getting to it now
